backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;

use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use frontend\models\PasswordChangeForm;
use frontend\models\MyResults;

use common\models\ContestUsers;
use common\models\User;
use common\models\LoginForm;
use common\models\Organizations;
use common\models\Requests;

/**
 * Site controller
 */
class SiteController extends Controller
{
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('success', 'Спасибо. Мы ответим вам на столько быстро, на сколько это возможно.');
            } else {
                Yii::$app->session->setFlash('error', 'Произошла ошибка при отправке письма.');
            }

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $model = new SignupForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }
        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Проверьте, что ваш email верный.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Извините, мы не можем восстановить пароль для предоставленного email.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Новый пароль сохранен.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
    
    public function actionPersonalarea(){
      
       $user = ContestUsers::findOne(Yii::$app->user->identity->getId());
       $organization = Organizations::findOne($user->organizationkey);
        return $this->render('personalArea',
                ['user'=>$user,
                    'organization'=>$organization->organizationname,
                ]);
        
    }
    public function actionPasswordChange()
    {
        $user = User::findOne(Yii::$app->user->identity->getId());
        $model = new PasswordChangeForm($user);
 
        if ($model->load(Yii::$app->request->post()) && $model->changePassword()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('passwordChange', [
                'model' => $model,
            ]);
        }
    }
    
    public function actionUpdate()
    {
        $model = ContestUsers::findOne(Yii::$app->user->identity->getId());
        
 
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            $organizations = Organizations::find()->all();
            $items = ArrayHelper::map($organizations,'organizationkey','organizationname');
            $params = [
                'prompt' => 'Выберите организацию'
            ];
            return $this->render('update', [
                'model' => $model,
                'items' => $items,
                'params'=>$params,
            ]);
        }
    }
    
    public function actionResults(){
        
        
        
        $id = Yii::$app->user->identity->getId();
        
        $sql = "Select
        con.contestkey,
	con.contestname,
	con.`condition`,
	rq.worklink,
	count(rs.mark) as myresult
        from requests rq 
        left join results rs on rs.requestkey = rq.requestkey
        left join contests  con on con.contestkey = rq.contestkey
        where rq.userkey = $id
        order by rq.requestkey";
        
        $results = MyResults::findBySql($sql);
        $dataProvider = $results->search(Yii::$app->request->queryParams);

        return $this->render('results', [
                'model' => $results,
                'dataProvider'=>$dataProvider,
                
            ]);
    }
    
}

frontend/views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'О сайте';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Информация о сайте</p>

    <code><?= __FILE__ ?></code>
</div>

frontend/views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Обратная связь.';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
       Заполните форму для обратной связи. 
    </p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'subject') ?>

                <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>

</div>

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\helpers\Html;
$this->title = 'Сайт конкурсов';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Добро пожаловать на сайт конкурсов!</h1>

    </div>

    <div class="body-content">

        <div class="row">
            <div class="col-lg-4">
                <h2>Конкурсы</h2>

                <p>Список текущих конкурсов</p>

                <p><?= Html::a('Конкурсы', ['/contests/index'],['class'=>'btn btn-default']) ?></p>
            </div>
            <?php if (Yii::$app->user->isGuest){
                $htmlCode = "<div class=\"col-lg-4\">
                
                <h2>Регистрация</h2>

                <p>Пройдите регистрацию по данной ссылке для участия в конкурсах</p><p>";
                $htmlCode.= Html::a('Регистрация', ['/site/signup'],['class'=>'btn btn-default']);
                $htmlCode.="</p></div>";
                echo Html::decode($htmlCode);
            }
            ?>
            <div class="col-lg-4">
                <h2>Результаты проведенных конкурсов</h2>

                <p>Пройдите по данной ссылке чтобы увидеть результаты прошедших конкурсов</p>

                <p><?= Html::a('Результаты', ['/results/index'],['class'=>'btn btn-default']) ?></p>
            </div>
        </div>

    </div>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожайлуста введите данные для входа:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div style="color:#999;margin:1em 0">
                    If you forgot your password you can <?= Html::a('reset it', ['site/request-password-reset']) ?>.
                </div>

                <div class="form-group">
                    <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/passwordChange.php
<?php
 
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

 
 
$this->params['breadcrumbs'][] = ['label'=>'Основное', 'url'=> Yii::$app->urlManager->createUrl(['site/personalarea'])];
$this->params['breadcrumbs'][] = ['label'=>'Настройки'];
   
?>
<div class="user-profile-password-change">
 
    <h1><?= Html::encode($this->title) ?></h1>
 
    <div class="user-form">
 
        <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($model, 'currentPassword')->passwordInput(['maxlength' => true])->label('Существующий пароль') ?>
        <?= $form->field($model, 'newPassword')->passwordInput(['maxlength' => true])->label('Новый пароль') ?>
        <?= $form->field($model, 'newPasswordRepeat')->passwordInput(['maxlength' => true])->label('Повторите новый пароль') ?>
 
        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Сохранить'), ['class' => 'btn btn-primary']) ?>
        </div>
 
        <?php ActiveForm::end(); ?>
 
    </div>
 
</div>

frontend/views/site/personalArea.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\ActiveForm;




$this->params['breadcrumbs'][] = ['label'=>'Основное'];
$this->params['breadcrumbs'][] = ['label'=>'Настройки', 'url'=> Yii::$app->urlManager->createUrl(['site/password-change'])];
   


?>

<p>
        <?= Html::a(Yii::t('app', 'Редактировать'), ['update'], ['class' => 'btn btn-primary']) ?>
    </p>

    <div class="user-profile">
 
    <h1><?= Html::encode($this->title) ?></h1>
 
    <?php
    switch ($user->role)
    {
        case \common\models\User::ROLE_USER: $role ='Пользователь'; break;
        case \common\models\User::ROLE_MODER: $role ='Проверяющий'; break;
        case \common\models\User::ROLE_ADMIN: $role ='Администратор'; break;
        default: $role = 'Роль не определена'; break;
    }

    echo DetailView::widget([
        'model' => $user,
        'attributes' => [
            'lastname',
            'firstname',
            'secondname',
            'birthday',
            [
                'attribute' => 'role',
                'value' => $role
            ],
            'email',
            'phonenumber',
            [
              'label'=>'Организация',
              'value'=>$organization,
            ],
        ],
    ]) ?>
 
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Запросить пароль';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/resetPassword.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\ResetPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Сбросить пароль';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-reset-password">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Введите новый пароль:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'reset-password-form']); ?>

                <?= $form->field($model, 'password')->passwordInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Сбросить', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\jui\DatePicker;

$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Пожалуйста, заполните следующие поля для регистрации:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'firstname')?>
                <?= $form->field($model, 'secondname')?>
                <?= $form->field($model, 'lastname')?>
                <?=$form->field($model, 'birthday')->textInput()->widget(DatePicker::className(), array(
                    'language' => 'ru',
                    'dateFormat' => 'yyyy-MM-dd',));?>
                <?php
                    $organizations = \common\models\Organizations::find()->all();
                    $items = \yii\helpers\ArrayHelper::map($organizations,'organizationkey','organizationname');
                ?>
                <?= $form->field($model, 'organization')->dropDownList($items)?>

                <div class="form-group">
                    <?= Html::submitButton('Регистрация', ['class' => 'btn btn-primary', 'name' => 'signup-button'])
                    ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/update.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use yii\jui\DatePicker;
use yii\widgets\MaskedInput;

$this->params['breadcrumbs'][] = ['label'=>'Основное', 'url'=> Yii::$app->urlManager->createUrl(['site/personalarea'])];
$this->params['breadcrumbs'][] = ['label'=>'Настройки', 'url'=> Yii::$app->urlManager->createUrl(['site/password-change'])];

?>
<div class="user-profile-update">
 
    <h1><?= Html::encode($this->title) ?></h1>
 
    <div class="user-form">
 
        <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($model, 'lastname')->textInput() ?>
        <?= $form->field($model, 'firstname')->textInput() ?>
        <?= $form->field($model, 'secondname')->textInput() ?>
        <?= $form->field($model, 'birthday')->textInput()->widget(DatePicker::className(), array(
            'language' => 'ru',
            'dateFormat' => 'yyyy-MM-dd',
            )
        ); ?>
        <?= $form->field($model, 'email')->textInput(['maxlength' => true]) ?>
        <?= $form->field($model, 'phonenumber')->textInput()-> widget(MaskedInput::className(), [
            'mask' => '+7 (999) 999 99 99']); ?>
        <?= $form->field($model, 'organizationkey')->dropDownList($items,$params) ?>
        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Сохранить'), ['class' => 'btn btn-primary']) ?>
        </div>
 
        <?php ActiveForm::end(); ?>
 
    </div>
 
</div>